package com.zhidao.kstb.model.tab;

import lombok.Data;

/**
 * 常住人口迁入申请审批信息
 *
 * @author <致道科技>YunTong
 * <p>Created on 2021-9-17<p>
 */
@Data
public class CZRK_QRSQSPXX {
    private Integer xlh;
    private Integer spglxlh;
    private String rkxlh;
    private String sqh;
    private String gmsfhm;
    private String xm;
    private String cym;
    private String xb;
    private String mz;
    private String csrq;
    private String cssj;
    private String csdgj;
    private String csdssx;
    private String csdxz;
    private String jggj;
    private String jgssx;
    private String jgxz;
    private String zjxy;
    private String whcd;
    private String hyzk;
    private String byzk;
    private String sg;
    private String xx;
    private String zy;
    private String zylb;
    private String dwbm;
    private String fwcs;
    private String xxjb;
    private String hh;
    private String sbrgmsfhm;
    private String sbrxm;
    private String sbrq;
    private String sblb;
    private String sbly;
    private String sldwjgdm;
    private String sldwmc;
    private String slrxm;
    private String slsj;
    private String dqm;
    private String ssxq;
    private String dzbm;
    private String xz;
    private String fxjdm;
    private String pcsdm;
    private String pcsjgmc;
    private String jwqdm;
    private String jwqmc;
    private String xzjddm;
    private String spqk;
    private String spdwjgdm;
    private String spdwmc;
    private String sprxm;
    private String spsj;
    private String spjg;
    private String lxdh;
    private String sqjcwhdm;
    private String sqjcwhmc;
    private Integer blqk;
    private String hlx;
    private String spjb;
    private String qsrq;
    private Integer shspzt;
    private String ywfl;
    private String shsplc;
    private String spyyms;
    private String spbh;
    private Integer sppzxlh;
    private String bz;
    private String shspyj;
    private String ysqrgx;
    private String slrid;
    private String sprid;
    private String xmpy;
    private String ywblsj;
    private String qrlb;
    private String bdqyfw;
    private String qcdssx;
    private String qcdxz;
    private String btkrgmsfhm;
    private String btkrxm;
    private String ytkrgx;
    private String spjgdm;
    private String cxfl;
    private String xcrkzczrkyy;
    private String bdywswbh;
    private String spywfl;
    private String ospjb;
    private String qcdgj;
    private String qyrhkdjjgdm;
    private String qyrhkdjjgmc;
    private String qrdhkdjjgdm;
    private String qrdhkdjjgmc;
    private String sqrssx;
    private String sqrxz;
    private String zqzbh;
    private Integer qctbs;
    private String slpcsdm;
    private Integer xpxlh;
    private String qyzlb;
    private String fhzc;
    private Integer hlwslbz;
    private String hlwid;
    private String rczl;
    private String qrzlb;
    private String cyzs;
    private String sqzxlb;
    private String sqzxms;
    private String sqtsbs;
    private String sqtsjg;
    private String kstbbs;
    private String ywxtbh;
}
